/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cmsc_405_project_2;

import javax.swing.JFrame;

import com.jogamp.opengl.GL;
import com.jogamp.opengl.GL2;
import com.jogamp.opengl.GLAutoDrawable;
import com.jogamp.opengl.GLCapabilities;
import com.jogamp.opengl.GLEventListener;
import com.jogamp.opengl.GLProfile;
import com.jogamp.opengl.awt.GLCanvas;

public class App extends JFrame implements GLEventListener {
    public App() {
        // Setting up the GLCanvas and frame
        GLProfile profile = GLProfile.get(GLProfile.GL2);
        GLCapabilities capabilities = new GLCapabilities(profile);
        GLCanvas canvas = new GLCanvas(capabilities);
        canvas.addGLEventListener(this);
        this.setName("Letter A Display");
        this.getContentPane().add(canvas);
        this.setSize(640, 480);
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setVisible(true);
        canvas.requestFocusInWindow();
    }

    public static void main(String[] args) {
        new App();
    }

    @Override
    public void init(GLAutoDrawable drawable) {
        GL2 gl = drawable.getGL().getGL2();
        gl.glClearColor(1, 1, 1, 1);
    }

    @Override
    public void dispose(GLAutoDrawable drawable) {
        // Resource cleanup
    }

    @Override
    public void display(GLAutoDrawable drawable) {
        GL2 gl = drawable.getGL().getGL2();
        gl.glClear(GL.GL_COLOR_BUFFER_BIT | GL.GL_DEPTH_BUFFER_BIT);

        // Set drawing color to something visible against the clear color
        gl.glColor3f(1.0f, 0.0f, 0.0f);

        // Drawing "CMSC 405" as a series of lines
        drawC(gl);
        drawM(gl);
        drawS(gl);
        drawC(gl);
        drawSpace(gl);
        draw4(gl);
        draw0(gl);
        draw5(gl);
    }

    private void drawC(GL2 gl) {
        gl.glBegin(GL2.GL_LINES);
        gl.glVertex2f(-0.9f, 0.1f);
        gl.glVertex2f(-0.7f, 0.1f);

        gl.glVertex2f(-0.9f, 0.1f);
        gl.glVertex2f(-0.9f, -0.1f);

        gl.glVertex2f(-0.9f, -0.1f);
        gl.glVertex2f(-0.7f, -0.1f);
        gl.glEnd();
    }

    private void drawM(GL2 gl) {
        gl.glBegin(GL2.GL_LINES);
        gl.glVertex2f(-0.6f, 0.1f);
        gl.glVertex2f(-0.6f, -0.1f);

        gl.glVertex2f(-0.6f, 0.1f);
        gl.glVertex2f(-0.5f, 0.0f);

        gl.glVertex2f(-0.5f, 0.0f);
        gl.glVertex2f(-0.4f, 0.1f);

        gl.glVertex2f(-0.4f, 0.1f);
        gl.glVertex2f(-0.4f, -0.1f);
        gl.glEnd();
    }

    private void drawS(GL2 gl) {
        gl.glBegin(GL2.GL_LINES);
        gl.glVertex2f(-0.3f, 0.1f);
        gl.glVertex2f(-0.1f, 0.1f);

        gl.glVertex2f(-0.3f, 0.1f);
        gl.glVertex2f(-0.3f, 0.0f);

        gl.glVertex2f(-0.3f, 0.0f);
        gl.glVertex2f(-0.1f, 0.0f);

        gl.glVertex2f(-0.1f, 0.0f);
        gl.glVertex2f(-0.1f, -0.1f);

        gl.glVertex2f(-0.1f, -0.1f);
        gl.glVertex2f(-0.3f, -0.1f);
        gl.glEnd();
    }

    private void drawSpace(GL2 gl) {
        // Space does not draw anything, it just translates the position for the next
        // character.
    }

    private void draw4(GL2 gl) {
        gl.glBegin(GL2.GL_LINES);
        gl.glVertex2f(0.0f, 0.1f);
        gl.glVertex2f(0.0f, -0.1f);

        gl.glVertex2f(0.0f, 0.1f);
        gl.glVertex2f(0.1f, 0.1f);

        gl.glVertex2f(0.1f, 0.1f);
        gl.glVertex2f(0.1f, -0.1f);

        gl.glVertex2f(0.0f, 0.0f);
        gl.glVertex2f(0.2f, 0.0f);
        gl.glEnd();
    }

    private void draw0(GL2 gl) {
        gl.glBegin(GL2.GL_LINES);
        gl.glVertex2f(0.3f, 0.1f);
        gl.glVertex2f(0.3f, -0.1f);

        gl.glVertex2f(0.3f, 0.1f);
        gl.glVertex2f(0.5f, 0.1f);

        gl.glVertex2f(0.5f, 0.1f);
        gl.glVertex2f(0.5f, -0.1f);

        gl.glVertex2f(0.3f, -0.1f);
        gl.glVertex2f(0.5f, -0.1f);
        gl.glEnd();
    }

    private void draw5(GL2 gl) {
        gl.glBegin(GL2.GL_LINES);
        gl.glVertex2f(0.6f, 0.1f);
        gl.glVertex2f(0.8f, 0.1f);

        gl.glVertex2f(0.6f, 0.1f);
        gl.glVertex2f(0.6f, 0.0f);

        gl.glVertex2f(0.6f, 0.0f);
        gl.glVertex2f(0.8f, 0.0f);

        gl.glVertex2f(0.8f, 0.0f);
        gl.glVertex2f(0.8f, -0.1f);

        gl.glVertex2f(0.6f, -0.1f);
        gl.glVertex2f(0.8f, -0.1f);
        gl.glEnd();
    }

    @Override
    public void reshape(GLAutoDrawable drawable, int x, int y, int width, int height) {
        GL2 gl = drawable.getGL().getGL2();
        gl.glViewport(0, 0, width, height);
    }

    public String getGreeting() {
        return "Hello World!";
    }
}
